#!/usr/bin/env bash
# This code counts from 0 to 9 and prints "Hi" when the count is 9

count=0

while [ $count -lt 10 ]
do
if [ $count -eq 9 ]
then
	echo "Hi"
fi
	echo "Best School"
count=$(( $count++ ))
done