#!/usr/bin/env bash
#print "Best School" in all iterations
#except:
#Iteration 4: prints `bad luck`
#Iteration 8: prints `good luck`

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]
    then
        echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( count++ ))
done