#!/usr/bin/env bash
#print "Best School" in all iterations
#except:
#Iteration 4: prints `bad luck from China`
#Iteration 9: prints `bad luck from Japan`
#Iteration 17 : prints `bad luck from Italy`

count=0

while [ $count -le 20 ]
do
    case $count in
        4	)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    (( count++ ))
done